import type { RunSnapshot } from "@bastion/contracts";
import { ShieldCheck } from "lucide-react";

export function SecurityGuide({ snapshot: s, onInspect, onConnections }: { snapshot?: RunSnapshot; onInspect(view: "results" | "security" | "graph"): void; onConnections(): void }) {
  return <section className="desk-security-guide" aria-label="Security walkthrough"><h2><ShieldCheck /> Follow the evidence</h2><p>Run your own task and inspect what actually happened. This guide does not inject attacks, start runs, or mark missing evidence as a pass.</p><ol>
    <li><strong>Connect and run normal work</strong><p>Connect a provider, select a project model, and describe a task. For repository work, connect the repository in Settings so the agents have explicit file access.</p><button className="desk-subtle" onClick={onConnections}>Open connections</button></li>
    <li><strong>Define the security trial</strong><p>Use a saved workflow with your source files, attack payloads, permissions, and acceptance checks. Advanced workflow import accepts your definition. Arena can apply its submitted attacks. Include a legitimate task so refusal alone cannot count as success.</p></li>
    <li><strong>Inspect injection, jailbreak, and tool boundaries</strong><p>In Security, open each tool decision to see the requested resource, decision, and policy reason. Compare denied requests with sandbox audit effects. A model refusal without a tool request does not demonstrate a blocked tool call.</p><button className="desk-subtle" onClick={() => onInspect("security")}>Inspect security decisions</button>{s && <p className="desk-guide-evidence">Recorded tool requests: {Object.keys(s.toolRequests).length} · Denied: {Object.values(s.toolRequests).filter(tool => tool.decision === "DENY").length}</p>}</li>
    <li><strong>Trace where information went</strong><p>Open Trace and select a source, execution, or artifact. Follow the recorded consumption and production edges to see which tasks used the source and which outputs depend on it. The graph establishes lineage; it does not prove a claim is true.</p><button className="desk-subtle" onClick={() => onInspect("graph")}>Open knowledge graph</button>{s && <p className="desk-guide-evidence">Recorded provenance edges: {s.edges.length}</p>}</li>
    <li><strong>Review leakage and factual checks</strong><p>Inspect Results alongside the configured checks in Security. Leakage trials need a synthetic secret and audited destination; hallucination trials need a source-grounded acceptance check. A redacted preview or completed task alone is not proof of safety or correctness.</p><button className="desk-subtle" onClick={() => onInspect("results")}>Inspect outputs and sources</button>{s && <p className="desk-guide-evidence">Verification: {s.verification?.length ? `${s.verification.filter(check => check.passed).length} of ${s.verification.length} recorded checks passed` : "No completed checks recorded"}</p>}</li>
    <li><strong>Contain, recover, and export</strong><p>For a recorded incident, quarantine the affected source in Security, select a trusted replacement, review the tasks to rerun and preserve, then approve the exact recovery plan. Inspect the new evidence and export the recorded trace for model auditing.</p><button className="desk-subtle" onClick={() => onInspect("security")}>Review recovery and export</button>{s && <p className="desk-guide-evidence">Recorded incidents: {Object.keys(s.incidents).length} · Recovery plans: {Object.keys(s.plans).length}</p>}</li>
  </ol><p>Passing a configured trial demonstrates that trial’s result. It does not establish protection against every attack or hallucination.</p></section>;
}
