import * as React from "react";
import * as Primitive from "@radix-ui/react-select";
import { Check, ChevronDown, ChevronUp } from "lucide-react";
import { cn } from "@/lib/utils";
export const Select = Primitive.Root;
export const SelectGroup = Primitive.Group;
export const SelectValue = Primitive.Value;
export const SelectTrigger = React.forwardRef<React.ElementRef<typeof Primitive.Trigger>, React.ComponentPropsWithoutRef<typeof Primitive.Trigger>>(({ className, children, ...props }, ref) => <Primitive.Trigger ref={ref} className={cn("control-select flex min-h-11 min-w-0 w-full items-center justify-between gap-3 rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground disabled:opacity-50 [&>span]:truncate", className)} {...props}>{children}<Primitive.Icon asChild><ChevronDown className="size-4 shrink-0 opacity-60" /></Primitive.Icon></Primitive.Trigger>);
SelectTrigger.displayName = "SelectTrigger";
export const SelectScrollUpButton = React.forwardRef<React.ElementRef<typeof Primitive.ScrollUpButton>, React.ComponentPropsWithoutRef<typeof Primitive.ScrollUpButton>>(({ className, ...props }, ref) => <Primitive.ScrollUpButton ref={ref} className={cn("flex justify-center py-1", className)} {...props}><ChevronUp className="size-4" /></Primitive.ScrollUpButton>);
SelectScrollUpButton.displayName = "SelectScrollUpButton";
export const SelectScrollDownButton = React.forwardRef<React.ElementRef<typeof Primitive.ScrollDownButton>, React.ComponentPropsWithoutRef<typeof Primitive.ScrollDownButton>>(({ className, ...props }, ref) => <Primitive.ScrollDownButton ref={ref} className={cn("flex justify-center py-1", className)} {...props}><ChevronDown className="size-4" /></Primitive.ScrollDownButton>);
SelectScrollDownButton.displayName = "SelectScrollDownButton";
export const SelectContent = React.forwardRef<React.ElementRef<typeof Primitive.Content>, React.ComponentPropsWithoutRef<typeof Primitive.Content> & { container?: HTMLElement | null }>(({ className, children, position = "popper", container, ...props }, ref) => <Primitive.Portal container={container}><Primitive.Content ref={ref} position={position} className={cn("control-popover relative z-50 max-h-[var(--radix-select-content-available-height)] min-w-[var(--radix-select-trigger-width)] overflow-hidden rounded-md border border-input bg-popover text-popover-foreground", className)} {...props}><SelectScrollUpButton /><Primitive.Viewport className="p-1">{children}</Primitive.Viewport><SelectScrollDownButton /></Primitive.Content></Primitive.Portal>);
SelectContent.displayName = "SelectContent";
export const SelectItem = React.forwardRef<React.ElementRef<typeof Primitive.Item>, React.ComponentPropsWithoutRef<typeof Primitive.Item>>(({ className, children, ...props }, ref) => <Primitive.Item ref={ref} className={cn("relative flex min-h-11 w-full cursor-default select-none items-center rounded-sm py-2 pl-8 pr-3 text-sm outline-none focus:bg-accent focus:text-accent-foreground data-[disabled]:opacity-50", className)} {...props}><span className="absolute left-2"><Primitive.ItemIndicator><Check className="size-4" /></Primitive.ItemIndicator></span><Primitive.ItemText>{children}</Primitive.ItemText></Primitive.Item>);
SelectItem.displayName = "SelectItem";
export const SelectLabel = Primitive.Label;
export const SelectSeparator = Primitive.Separator;
